### ISSUE TITLE
How to implement the second parameter in go language to false

### ISSUE THREAD

**Issue by ezewu** [apache/casbin-spring-boot-starter#10]
casbin.NewEnforcer(cfg.CasbinModelConf, false)

**Comment by fangzhengjin** [comment]
Sorry I didn't use go language. What's the second parameter you're referring to?

**Comment by ezewu** [comment]
The second parameter I'm referring to is how the Java library of false implements the second parameter passing false

**Comment by fangzhengjin** [comment]
What is the role of the second parameter false in the go language implementation?

**Comment by ezewu** [comment]
CSV files stored in database

**Comment by hsluoyz** [comment]
The 2nd arg in Golang's ``NewEnforcer()`` means ``enableLog``, see: https://casbin.org/docs/en/log-error

**Comment by fangzhengjin** [comment]
1. If you need to disable the log, you can set it after getting the enforcer object. In spring, the enforcer object is a singleton.
1. If you need to store the CSV file in the database, it is recommended to use the database tool to import directly, or you can provide a PR with this function.

**Comment by fangzhengjin** [comment]
1. If you need to disable the log, you can set it after getting the enforcer object. In spring, the enforcer object is a singleton.
2. If you need to store the CSV file in the database, it is recommended to use the database tool to import directly, you can also submit a PR for this function.
