### ISSUE TITLE
Support all enforcers types in AutoConfiguration

### ISSUE THREAD

**Issue by jay-babu** [apache/casbin-spring-boot-starter#101]
JCasbin officially supports DistributedEnforcer however there is no way to configure it with CasbinAutoConfiguration

https://github.com/casbin/jcasbin/blob/master/src/main/java/org/casbin/jcasbin/main/DistributedEnforcer.java

The ask is to support that enforcer via a properties. I can open a PR if this will be accepted

**Comment by hsluoyz** [comment]
@jay-babu can you make a PR?

**Comment by jay-babu** [comment]
@hsluoyz https://github.com/jcasbin/casbin-spring-boot-starter/pull/102
