### ISSUE TITLE
Delete Perm throws a CasbibException

### ISSUE THREAD

**Issue by 8rV1n** [apache/casbin-spring-boot-starter#11]
background:
spring boot project, with 2.1.7.RELEASE and casbin spring boot starter the latest

default model, with jdbc adapter

situation 1
put no data in the table of casbin_rule
excute enforcer.deletePermission("perm");

situation 2
put some data in the table of casbin_rule：
p,ROLE_ADMIN,res,add
g,admin,ROLE_ADMIN

excute `enforcer.deletePermission("res","delete");`
it will throw a Casbin Exception with info:
`CasbinAdapterException: Remove filtered policy error, remove 0 rows, expect least 1 rows`
I have debugged and found it's something wrong with the jdbc adapter.

**Comment by hsluoyz** [comment]
@fangzhengjin

**Comment by fangzhengjin** [comment]
Version 0.0.9 has been released
