### ISSUE TITLE
最简配置下 H2 如何生效的呢？

### ISSUE THREAD

**Issue by lianghujun** [apache/casbin-spring-boot-starter#14]
最简配置下 autoConfigJdbcAdapter入参 jdbcTemplate 默认使用的是h2 和HikariPool.
连接池HikariPool 是springboot 2.X  默认的  h2是怎么回事呢？

**Comment by hsluoyz** [comment]
@fangzhengjin

**Comment by fangzhengjin** [comment]
@lianghujun 因为 casbin-spring-boot-starter 不推荐直接使用 FileAdapter 进行策略存储，并且只支持从 FileAdapter 读取策略（如需保存至文件需要重写FileAdapter），对于不使用 FileAdapter 并且未指定存储方式时，将会使用h2进行存储（默认存储在内存中），如需指定h2存档文件位置，可参考spring boot h2相关配置

**Comment by lianghujun** [comment]
谢谢啦，之前不懂自动配置原理。自己参考练习时没有配置resource/META-INF/spring.factories 。（后来的小伙伴正常集成是不需要配置的哈）
