### ISSUE TITLE
FilteredPolicy for JdbcAdapter

### ISSUE THREAD

**Issue by doandung2701** [apache/casbin-spring-boot-starter#16]
With large dataset policy in database,  JdbcAdapter need implement FilteredPolicy method allow load dynamic policy based on user

**Comment by hsluoyz** [comment]
@doandung2701 do you mean this repo? https://github.com/jcasbin/jdbc-adapter or still this Springboot starter repo?

**Comment by doandung2701** [comment]
@hsluoyz I want this repo. Because i am using spring-boot with this repo

**Comment by hsluoyz** [comment]
@fangzhengjin

**Comment by fangzhengjin** [comment]
I will deal with this problem after JCasbin adjusts the FilteredAdapter interface.

**Comment by hsluoyz** [comment]
Wait for: https://github.com/casbin/jcasbin/issues/107

**Comment by hsluoyz** [comment]
> I will deal with this problem after JCasbin adjusts the FilteredAdapter interface.

@fangzhengjin the PR: https://github.com/casbin/jcasbin/pull/116 is merged. FilteredAdapter interface is already added. I think we can fix this issue now?

**Comment by hsluoyz** [comment]
I think we should add the missing functions of of FilteredAdapter interface like `loadFilteredPolicy()` and `isFiltered()` to the JdbcAdapter class here: https://github.com/jcasbin/casbin-spring-boot-starter/blob/master/src/main/java/org/casbin/adapter/JdbcAdapter.java

**Comment by fangzhengjin** [comment]
Version 0.0.10 has been released.

**Comment by hsluoyz** [comment]
@doandung2701 see: https://github.com/jcasbin/casbin-spring-boot-starter/releases/tag/0.0.10

**Comment by barnesm999** [comment]
@fangzhengjin will 0.0.10 be added to Maven Central? Looks like it is still at 0.0.9 there.

**Comment by hsluoyz** [comment]
@fangzhengjin can we release 0.0.10 to Maven? https://search.maven.org/artifact/org.casbin/casbin-spring-boot-starter

**Comment by fangzhengjin** [comment]
@hsluoyz When Bintray synchronizes to Maven Central, it prompts: Failed to close repository: orgcasbin-1059. Dropping existing partial staging repository.

**Comment by hsluoyz** [comment]
@barnesm999 @fangzhengjin I think v0.0.10 is already pushed to Maven Central: https://search.maven.org/artifact/org.casbin/casbin-spring-boot-starter/0.0.10/jar
