### ISSUE TITLE
Impact of upgrading to 0.0.11 and later

### ISSUE THREAD

**Issue by fangzhengjin** [apache/casbin-spring-boot-starter#25]
Since version 0.0.11, casbin-spring-boot-starter adds an id field to the database table structure by default. 
The version before 0.0.11 is upgraded to version 0.0.11 and later requires the user to manually add the id field. 
See #21  for details

**Comment by hsluoyz** [comment]
@shy1st can you help put this warning in the README? So we can close the issue here.
