### ISSUE TITLE
Two databases

### ISSUE THREAD

**Issue by uPagge** [apache/casbin-spring-boot-starter#27]
I have two databases in my project

How can I tell which database to create tables in?

**Comment by hsluoyz** [comment]
@shy1st

**Comment by shy1st** [comment]
I think it depends on which data source you use as the default data source (master data source). After the container starts, casbin-spring-boot-starter will get the injected data source information to determine which database you are using, and then instantiate the corresponding adapter. @uPagge

**Comment by hsluoyz** [comment]
@fangzhengjin

**Comment by uPagge** [comment]
@shy1st Yes, I understand that. This is the problem, that I would like to use a different base than the default))

**Comment by fangzhengjin** [comment]
> @shy1st Yes, I understand that. This is the problem, that I would like to use a different base than the default))

1. For now, you can solve this problem by using a custom JdbcTemplate instead of the default JdbcTemplate used by Casbin.
2. Wait for us to release a new version that supports this feature (it will take some time).

**Comment by uPagge** [comment]
Got it, thanks for the answer)

**Comment by hsluoyz** [comment]
Can we make it customizable for the user?

**Comment by fangzhengjin** [comment]
Of course!


---Original---

**Comment by fangzhengjin** [comment]
Of course!



---Original---

**Comment by hsluoyz** [comment]
@shy1st

**Comment by hsluoyz** [comment]
@uPagge this issue has been fixed in: https://github.com/jcasbin/casbin-spring-boot-starter/pull/36
