### ISSUE TITLE
What is the use of casbin springboot starter?

### ISSUE THREAD

**Issue by divyagar** [apache/casbin-spring-boot-starter#28]
I saw [jcasbin springboot plugin](https://github.com/jcasbin/jcasbin-springboot-plugin). It is using jcasbin middleware instead of casbin springboot starter. If a springboot project can implement all the functionalities using jcasbin, what is the use of springboot starter?

**Comment by hsluoyz** [comment]
@divyagar https://github.com/jcasbin/jcasbin-springboot-plugin is deprecated, people should use this one.
