### ISSUE TITLE
Use semantic-release to automatically release new versions

### ISSUE THREAD

**Issue by hsluoyz** [apache/casbin-spring-boot-starter#37]
See how we did it for jCasbin: https://github.com/casbin/jcasbin/issues/76

**Comment by shy1st** [comment]
It will takes a little time, because this project is managed with gradle.

**Comment by hsluoyz** [comment]
@shy1st @fangzhengjin why don't we use Maven like jCasbin?

**Comment by fangzhengjin** [comment]
> @shy1st @fangzhengjin why don't we use Maven like jCasbin?

Maven is not as flexible and easy to use as Gradle, i haven't used Maven for a long time.

**Comment by shy1st** [comment]
![捕获](https://user-images.githubusercontent.com/34126552/113387967-e847fa80-93bf-11eb-9696-7da814c5d7b5.PNG)
Next I think we should replace bintray to nexus when release new versions of casbin-spring-boot-starter.

**Comment by fangzhengjin** [comment]
> ![捕获](https://user-images.githubusercontent.com/34126552/113387967-e847fa80-93bf-11eb-9696-7da814c5d7b5.PNG)
> Next I think we should replace bintray to nexus when release new versions of casbin-spring-boot-starter.

ok

**Comment by fangzhengjin** [comment]
@hsluoyz Please configure MAVEN_USERNAME and MAVEN_PASSWORD in encrypted secrets.

**Comment by hsluoyz** [comment]
> @hsluoyz Please configure MAVEN_USERNAME and MAVEN_PASSWORD in encrypted secrets.

Then we should move to Maven Central. @shy1st plz configure.

**Comment by shy1st** [comment]
@fangzhengjin I have finished the configuration.
![捕获](https://user-images.githubusercontent.com/34126552/113555057-e040c280-962c-11eb-92d6-fad258e79745.PNG)

**Comment by hsluoyz** [comment]
@shy1st plz release v0.1.0 to try it

**Comment by shy1st** [comment]
@hsluoyz Maybe we still need to modify some configuration to move to Maven Central. I want to use maven to replace the gradle.

**Comment by fangzhengjin** [comment]
What is the reason for migrating a project from gradle to maven?



---Original---
From: "Hongyang ***@***.***&gt;
Date: Mon, Apr 5, 2021 17:00 PM
To: ***@***.***&gt;;
Cc: "ZhengJin ***@***.******@***.***&gt;;
Subject: Re: [jcasbin/casbin-spring-boot-starter] Use semantic-release to automatically release new versions (#37)




 
@hsluoyz Maybe we still need to modify some configuration to move to Maven Central. I want to use maven to replace the gradle.

**Comment by hsluoyz** [comment]
@fangzhengjin @shy1st I think here are two things:

1. Maven Central is the package registry. Bintray will be down. So we will migrate to Maven Central.
2. Maven is the package manager tool. Does we have to use Maven to upload to Maven Central? Or Gradle can also be used? Or can we support both?

**Comment by fangzhengjin** [comment]
Of course, many large projects are built using gradle, and gradle's use of dependency libraries is also the central repository of maven.&nbsp;
Gradle can do the same things as maven, but it is more powerful than maven and can do things that maven can't do.



---Original---
From: ***@***.***&gt;
Date: Mon, Apr 5, 2021 17:26 PM
To: ***@***.***&gt;;
Cc: "ZhengJin ***@***.******@***.***&gt;;
Subject: Re: [jcasbin/casbin-spring-boot-starter] Use semantic-release to automatically release new versions (#37)




 
@fangzhengjin @shy1st I think here are two things:
  
Maven Central is the package registry. Bintray will be down. So we will migrate to Maven Central. 

Maven is the package manager tool. Does we have to use Maven to upload to Maven Central? Or Gradle can also be used? Or can we support both?

**Comment by hsluoyz** [comment]
@fangzhengjin thanks for explanation! Then I think we will use the Gradle + Maven Central combination.

**Comment by fangzhengjin** [comment]
I will deal with it when I have time.



---Original---
From: ***@***.***&gt;
Date: Mon, Apr 5, 2021 17:46 PM
To: ***@***.***&gt;;
Cc: "ZhengJin ***@***.******@***.***&gt;;
Subject: Re: [jcasbin/casbin-spring-boot-starter] Use semantic-release to automatically release new versions (#37)




 
@fangzhengjin thanks for explanation! Then I think we will use the Gradle + Maven Central combination.

**Comment by shy1st** [comment]
@hsluoyz @fangzhengjin 
I want to use maven for the reason that I had configured semantic-release of maven central.

**Comment by fangzhengjin** [comment]
@hsluoyz What do you think?

**Comment by hsluoyz** [comment]
@fangzhengjin if you can setup semantic-release on Gradle finally, I'm OK with both. Or we can keep both Gradle and Maven POM files in the repo. What do you think?
