### ISSUE TITLE
Redis Connection Failure

### ISSUE THREAD

**Issue by arti0798** [apache/casbin-spring-boot-starter#40]
Hey,
  there I m  trying to run this application where it get over with this error 'ERROR 21647 --- [enerContainer-1] o.s.d.r.l.RedisMessageListenerContainer : Connection failure occurred. Restarting subscription task after 5000 ms'

I have already tried with these combinations -

```gradle
plugins {
    id 'org.springframework.boot' version '2.3.5.RELEASE'
    id "com.jfrog.bintray" version "1.8.4"
    id 'java'
}

apply plugin: 'io.spring.dependency-management'
apply from: "maven.gradle"
apply from: "bintray.gradle"
apply from: "jacoco.gradle"

group = 'org.casbin'
version VERSION_CODE
sourceCompatibility = '1.8'
compileJava.options.encoding = 'UTF-8'

bootJar.enabled = false
jar.enabled = true

repositories {
    mavenLocal()
    maven { url "https://maven.aliyun.com/repository/public/" }
    mavenCentral()
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

dependencies {
    compile 'org.casbin:jcasbin:1.6.4'
    compile 'com.h2database:h2'
    implementation 'org.springframework.boot:spring-boot-starter-jdbc'

    compileOnly 'org.springframework.boot:spring-boot-starter-data-redis'
    testImplementation 'org.springframework.boot:spring-boot-starter-data-redis'
    testRuntimeOnly 'mysql:mysql-connector-java:5.1.47'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    implementation 'org.casbin:casbin-spring-boot-starter:version'
    // implementation 'org.springframework.boot:spring-boot-starter-data-redis:2.2.0.RELEASE'
    // implementation 'redis.clients:jedis:2.8.0'
    // implementation group: org.springframework.boot 
    // name: spring-boot-starter-data-redis 
    // version: 2.4.0-M3

}
```

But I m unable to run the application.

**Comment by hsluoyz** [comment]
@shy1st @fangzhengjin

**Comment by fangzhengjin** [comment]
There is no project repository that can reproduce the problem. I cannot check the problem.&nbsp;
I suspect that it is a connection problem with redis. We recommend that you try again after installing redis locally.



---Original---
From: "Arti ***@***.***&gt;
Date: Sat, Apr 3, 2021 00:08 AM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [jcasbin/casbin-spring-boot-starter] Redis Connection Failure (#40)




 
Hey,
 there I m  trying to run this application where it get over with this error 'ERROR 21647 --- [enerContainer-1] o.s.d.r.l.RedisMessageListenerContainer : Connection failure occurred. Restarting subscription task after 5000 ms'
 
I have already tried with these combinations -
 
plugins {
 id 'org.springframework.boot' version '2.3.5.RELEASE'
 id "com.jfrog.bintray" version "1.8.4"
 id 'java'
 }
 
apply plugin: 'io.spring.dependency-management'
 apply from: "maven.gradle"
 apply from: "bintray.gradle"
 apply from: "jacoco.gradle"
 
group = 'org.casbin'
 version VERSION_CODE
 sourceCompatibility = '1.8'
 compileJava.options.encoding = 'UTF-8'
 
bootJar.enabled = false
 jar.enabled = true
 
repositories {
 mavenLocal()
 maven { url "https://maven.aliyun.com/repository/public/" }
 mavenCentral()
 }
 
configurations {
 compileOnly {
 extendsFrom annotationProcessor
 }
 }
 
dependencies {
 compile 'org.casbin:jcasbin:1.6.4'
 compile 'com.h2database:h2'
 implementation 'org.springframework.boot:spring-boot-starter-jdbc'
 compileOnly 'org.springframework.boot:spring-boot-starter-data-redis' testImplementation 'org.springframework.boot:spring-boot-starter-data-redis' testRuntimeOnly 'mysql:mysql-connector-java:5.1.47' testImplementation 'org.springframework.boot:spring-boot-starter-test' implementation 'org.casbin:casbin-spring-boot-starter:version' // implementation 'org.springframework.boot:spring-boot-starter-data-redis:2.2.0.RELEASE' // implementation 'redis.clients:jedis:2.8.0' // implementation group: org.springframework.boot  // name: spring-boot-starter-data-redis  // version: 2.4.0-M3  
}
 
But I m unable to run the application.

**Comment by shink** [comment]
@arti0798 Well, have you configured spring-data-redis in src/main/resources/application.yml? Such as:

```yml
spring:
  redis:
    host: your_host
    port: your_port
```

Or you can show we your configuration here.

**Comment by arti0798** [comment]
> @arti0798 Well, have you configured spring-data-redis in src/main/resources/application.yml? Such as:
> 
> ```yaml
> spring:
>   redis:
>     host: your_host
>     port: your_port
> ```
> 
> Or you can show we your configuration here.

yeah! 

redis:
    host: localhost
    port: 6379

**Comment by arti0798** [comment]
> There is no project repository that can reproduce the problem. I cannot check the problem.&nbsp; I suspect that it is a connection problem with redis. We recommend that you try again after installing redis locally.
> […](#)
> ---Original--- From: "Arti ***@***.***&gt; Date: Sat, Apr 3, 2021 00:08 AM To: ***@***.***&gt;; Cc: ***@***.***&gt;; Subject: [jcasbin/casbin-spring-boot-starter] Redis Connection Failure (#40) Hey, there I m trying to run this application where it get over with this error 'ERROR 21647 --- [enerContainer-1] o.s.d.r.l.RedisMessageListenerContainer : Connection failure occurred. Restarting subscription task after 5000 ms' I have already tried with these combinations - plugins { id 'org.springframework.boot' version '2.3.5.RELEASE' id "com.jfrog.bintray" version "1.8.4" id 'java' } apply plugin: 'io.spring.dependency-management' apply from: "maven.gradle" apply from: "bintray.gradle" apply from: "jacoco.gradle" group = 'org.casbin' version VERSION_CODE sourceCompatibility = '1.8' compileJava.options.encoding = 'UTF-8' bootJar.enabled = false jar.enabled = true repositories { mavenLocal() maven { url "https://maven.aliyun.com/repository/public/" } mavenCentral() } configurations { compileOnly { extendsFrom annotationProcessor } } dependencies { compile 'org.casbin:jcasbin:1.6.4' compile 'com.h2database:h2' implementation 'org.springframework.boot:spring-boot-starter-jdbc' compileOnly 'org.springframework.boot:spring-boot-starter-data-redis' testImplementation 'org.springframework.boot:spring-boot-starter-data-redis' testRuntimeOnly 'mysql:mysql-connector-java:5.1.47' testImplementation 'org.springframework.boot:spring-boot-starter-test' implementation 'org.casbin:casbin-spring-boot-starter:version' // implementation 'org.springframework.boot:spring-boot-starter-data-redis:2.2.0.RELEASE' // implementation 'redis.clients:jedis:2.8.0' // implementation group: org.springframework.boot // name: spring-boot-starter-data-redis // version: 2.4.0-M3 } But I m unable to run the application. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

okay! I will try again.

**Comment by arti0798** [comment]
> There is no project repository that can reproduce the problem. I cannot check the problem.&nbsp; I suspect that it is a connection problem with redis. We recommend that you try again after installing redis locally.
> […](#)
> ---Original--- From: "Arti ***@***.***&gt; Date: Sat, Apr 3, 2021 00:08 AM To: ***@***.***&gt;; Cc: ***@***.***&gt;; Subject: [jcasbin/casbin-spring-boot-starter] Redis Connection Failure (#40) Hey, there I m trying to run this application where it get over with this error 'ERROR 21647 --- [enerContainer-1] o.s.d.r.l.RedisMessageListenerContainer : Connection failure occurred. Restarting subscription task after 5000 ms' I have already tried with these combinations - plugins { id 'org.springframework.boot' version '2.3.5.RELEASE' id "com.jfrog.bintray" version "1.8.4" id 'java' } apply plugin: 'io.spring.dependency-management' apply from: "maven.gradle" apply from: "bintray.gradle" apply from: "jacoco.gradle" group = 'org.casbin' version VERSION_CODE sourceCompatibility = '1.8' compileJava.options.encoding = 'UTF-8' bootJar.enabled = false jar.enabled = true repositories { mavenLocal() maven { url "https://maven.aliyun.com/repository/public/" } mavenCentral() } configurations { compileOnly { extendsFrom annotationProcessor } } dependencies { compile 'org.casbin:jcasbin:1.6.4' compile 'com.h2database:h2' implementation 'org.springframework.boot:spring-boot-starter-jdbc' compileOnly 'org.springframework.boot:spring-boot-starter-data-redis' testImplementation 'org.springframework.boot:spring-boot-starter-data-redis' testRuntimeOnly 'mysql:mysql-connector-java:5.1.47' testImplementation 'org.springframework.boot:spring-boot-starter-test' implementation 'org.casbin:casbin-spring-boot-starter:version' // implementation 'org.springframework.boot:spring-boot-starter-data-redis:2.2.0.RELEASE' // implementation 'redis.clients:jedis:2.8.0' // implementation group: org.springframework.boot // name: spring-boot-starter-data-redis // version: 2.4.0-M3 } But I m unable to run the application. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

okay! I will try again.
