### ISSUE TITLE
JDBC Adapter for PostgreSQL fails for creation of Table

### ISSUE THREAD

**Issue by byrebg** [apache/casbin-spring-boot-starter#44]
Hi Team,

casbin-spring-boot-starter - Version used - 0.0.13
postgresql version - 10.10

Currently I am integrating the casbin sprin boot starter using the JDBCAdapter for - PostgreSQL. I am encountering following execption during the table creation

2021-05-27 15:38:08.306 DEBUG 25048 --- [           main] o.s.jdbc.core.JdbcTemplate               : Executing SQL statement [CREATE TABLE IF NOT EXISTS casbin_rule (    id int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,     ptype varchar(255) NOT NULL,    v0    varchar(255) DEFAULT NULL,    v1    varchar(255) DEFAULT NULL,    v2    varchar(255) DEFAULT NULL,    v3    varchar(255) DEFAULT NULL,    v4    varchar(255) DEFAULT NULL,    v5    varchar(255) DEFAULT NULL)]
2021-05-27 15:38:08.383  WARN 25048 --- [           main] s.c.a.AnnotationConfigApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'authorizationCMDStartup': Unsatisfied dependency expressed through field 'rbacDBTest'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'RBACdbTest': Unsatisfied dependency expressed through field 'adapter'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'autoConfigJdbcAdapter' defined in class path resource [org/casbin/spring/boot/autoconfigure/CasbinAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.casbin.jcasbin.persist.Adapter]: Factory method 'autoConfigJdbcAdapter' threw exception; nested exception is org.springframework.jdbc.BadSqlGrammarException: StatementCallback; bad SQL grammar [CREATE TABLE IF NOT EXISTS casbin_rule (    id int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,     ptype varchar(255) NOT NULL,    v0    varchar(255) DEFAULT NULL,    v1    varchar(255) DEFAULT NULL,    v2    varchar(255) DEFAULT NULL,    v3    varchar(255) DEFAULT NULL,    v4    varchar(255) DEFAULT NULL,    v5    varchar(255) DEFAULT NULL)]; nested exception is org.postgresql.util.PSQLException: ERROR: syntax error at or near "("
  Position: 51

On debugging deeper, I found in JDBC Adapter the "INIT TABLE SQL" throws the syntax error for PostgreSQL
Tried executing same in PostgreSQL editor
![image](https://user-images.githubusercontent.com/1397426/119836991-7b099f00-bf02-11eb-8712-7643d6f79ba5.png)

Could suggest or guide on this ?

**Comment by fangzhengjin** [comment]
Can you provide the correct SQL statement used in the PostgreSQL? For example, create a table or delete a table.&nbsp;
You can also submit the pr implementation PostgreSQL adapter to help us solve this problem.




---Original---
From: ***@***.***&gt;
Date: Thu, May 27, 2021 21:47 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [jcasbin/casbin-spring-boot-starter] JDBC Adapter for PostgreSQL fails for creation of Table (#44)




 
Hi Team,
 
casbin-spring-boot-starter - Version used - 0.0.13
 postgresql version - 10.10
 
Currently I am integrating the casbin sprin boot starter using the JDBCAdapter for - PostgreSQL. I am encountering following execption during the table creation
 
2021-05-27 15:38:08.306 DEBUG 25048 --- [           main] o.s.jdbc.core.JdbcTemplate               : Executing SQL statement [CREATE TABLE IF NOT EXISTS casbin_rule (    id int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,     ptype varchar(255) NOT NULL,    v0    varchar(255) DEFAULT NULL,    v1    varchar(255) DEFAULT NULL,    v2    varchar(255) DEFAULT NULL,    v3    varchar(255) DEFAULT NULL,    v4    varchar(255) DEFAULT NULL,    v5    varchar(255) DEFAULT NULL)]
 2021-05-27 15:38:08.383  WARN 25048 --- [           main] s.c.a.AnnotationConfigApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'authorizationCMDStartup': Unsatisfied dependency expressed through field 'rbacDBTest'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'RBACdbTest': Unsatisfied dependency expressed through field 'adapter'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'autoConfigJdbcAdapter' defined in class path resource [org/casbin/spring/boot/autoconfigure/CasbinAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.casbin.jcasbin.persist.Adapter]: Factory method 'autoConfigJdbcAdapter' threw exception; nested exception is org.springframework.jdbc.BadSqlGrammarException: StatementCallback; bad SQL grammar [CREATE TABLE IF NOT EXISTS casbin_rule (    id int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,     ptype varchar(255) NOT NULL,    v0    varchar(255) DEFAULT NULL,    v1    varchar(255) DEFAULT NULL,    v2    varchar(255) DEFAULT NULL,    v3    varchar(255) DEFAULT NULL,    v4    varchar(255) DEFAULT NULL,    v5    varchar(255) DEFAULT NULL)]; nested exception is org.postgresql.util.PSQLException: ERROR: syntax error at or near "("
 Position: 51
 
On debugging deeper, I found in JDBC Adapter the "INIT TABLE SQL" throws the syntax error for PostgreSQL
 Tried executing same in PostgreSQL editor
 
 
Could suggest or guide on this ?

**Comment by byrebg** [comment]
Hi,
Thanks for feedback. 
I checked the following syntax from JDBCAdapter in Query editor of PostgreSQL

```java
 private final static String DROP_TABLE_SQL = "DROP TABLE IF EXISTS casbin_rule";
 private final static String DELETE_TABLE_CONTENT_SQL = "DELETE FROM casbin_rule";
 private final static String LOAD_POLICY_SQL = "SELECT * FROM casbin_rule";
 private final static String INSERT_POLICY_SQL = "INSERT INTO casbin_rule(ptype, v0, v1, v2, v3, v4, v5) VALUES(?, ?, ?, ?, ?, ?, ?)";
 private final static String DELETE_POLICY_SQL = "DELETE FROM casbin_rule WHERE ptype = ? ";
```

**These work fine.**

Issue is with creation of table syntax. The one highlighted 

**Not working** 

```java
private final static String INIT_TABLE_SQL = "CREATE TABLE IF NOT EXISTS casbin_rule (" +
            "    **id int_(11) NOT NULL AUTO_INCREMENT_ PRIMARY KEY,** "+
            "    ptype varchar(255) NOT NULL," +
            "    v0    varchar(255) DEFAULT NULL," +
            "    v1    varchar(255) DEFAULT NULL," +
            "    v2    varchar(255) DEFAULT NULL," +
            "    v3    varchar(255) DEFAULT NULL," +
            "    v4    varchar(255) DEFAULT NULL," +
            "    v5    varchar(255) DEFAULT NULL" +
            ")";
```

To be changed

```java
private final static String INIT_TABLE_SQL = "CREATE TABLE IF NOT EXISTS casbin_rule (" +
            "    id SERIAL PRIMARY KEY, "+
            "    ptype varchar(255) NOT NULL," +
            "    v0    varchar(255) DEFAULT NULL," +
            "    v1    varchar(255) DEFAULT NULL," +
            "    v2    varchar(255) DEFAULT NULL," +
            "    v3    varchar(255) DEFAULT NULL," +
            "    v4    varchar(255) DEFAULT NULL," +
            "    v5    varchar(255) DEFAULT NULL" +
            ")";
```

Reason - PostgreSQL does not support syntax id int (11) and AUTO INCREMENT. 
https://chartio.com/resources/tutorials/how-to-define-an-auto-increment-primary-key-in-postgresql/

I have tested with PostgreSQL editor  after changing the syntax and it works fine

![image](https://user-images.githubusercontent.com/1397426/119846141-29651280-bf0a-11eb-88bd-94a440fa8240.png)

**Comment by hsluoyz** [comment]
@byrebg can you make a PR to fix it?

**Comment by byrebg** [comment]
Hi,
Thanks for the changes, but there one slight things is missed. I am still facing the issue

Version tested - 0.1.1

Reason : 
```java
@Bean
    @ConditionalOnProperty(name = "casbin.storeType", havingValue = "jdbc", matchIfMissing = true)
    @ConditionalOnBean(JdbcTemplate.class)
    @ConditionalOnMissingBean
    @SuppressWarnings("SpringJavaInjectionPointsAutowiringInspection")
    public Adapter autoConfigJdbcAdapter(
            @CasbinDataSource ObjectProvider<DataSource> casbinDataSource,
            JdbcTemplate jdbcTemplate,
            CasbinProperties properties,
            CasbinExceptionProperties exceptionProperties
    ) {
        JdbcTemplate jdbcTemplateToUse = getJdbcTemplate(jdbcTemplate, casbinDataSource);
        String databaseName = getDatabaseName(jdbcTemplateToUse.getDataSource());
        CasbinDataSourceInitializationMode initializeSchema = properties.getInitializeSchema();
        boolean autoCreateTable = initializeSchema == CasbinDataSourceInitializationMode.CREATE;
        logger.info("Casbin current use database product: {}", databaseName);
        switch (databaseName) {
            case "mysql":
            case "h2":
            case "postgresql":
                return new JdbcAdapter(jdbcTemplateToUse, exceptionProperties, autoCreateTable);
            case "oracle":
                return new OracleAdapter(jdbcTemplateToUse, exceptionProperties, autoCreateTable);
            case "db2":
                return new DB2Adapter(jdbcTemplateToUse, exceptionProperties, autoCreateTable);
            default:
                throw new CasbinAdapterException("Can't find " + databaseName + " jdbc adapter");
        }
    }

```

This code needs to be changed to create the new PostgreSQLAdapter object.
Switch case needs to be changed

```java
 switch (databaseName) {
            case "mysql":
            case "h2":
                return new JdbcAdapter(jdbcTemplateToUse, exceptionProperties, autoCreateTable);
            case "postgresql":
                return new PostgreSQLAdapter(jdbcTemplateToUse, exceptionProperties, autoCreateTable);
            case "oracle":
                return new OracleAdapter(jdbcTemplateToUse, exceptionProperties, autoCreateTable);
            case "db2":
                return new DB2Adapter(jdbcTemplateToUse, exceptionProperties, autoCreateTable);
            default:
                throw new CasbinAdapterException("Can't find " + databaseName + " jdbc adapter");
        }
```

Let me know if i need to create a new issue or the current ticket can be reopened ?

**Comment by fangzhengjin** [comment]
If it is convenient, can you submit a PR to solve this problem?

**Comment by byrebg** [comment]
Currently I have some technical issues due to firewall to do. I have added the snippet if it help. 

```java
package org.casbin.spring.boot.autoconfigure;

import org.casbin.adapter.DB2Adapter;
import org.casbin.adapter.JdbcAdapter;
import org.casbin.adapter.OracleAdapter;
import org.casbin.adapter.PostgreSQLAdapter;
import org.casbin.annotation.CasbinDataSource;
import org.casbin.exception.CasbinAdapterException;
import org.casbin.exception.CasbinModelConfigNotFoundException;
import org.casbin.jcasbin.main.Enforcer;
import org.casbin.jcasbin.main.SyncedEnforcer;
import org.casbin.jcasbin.model.Model;
import org.casbin.jcasbin.persist.Adapter;
import org.casbin.jcasbin.persist.file_adapter.FileAdapter;
import org.casbin.spring.boot.autoconfigure.properties.CasbinDataSourceInitializationMode;
import org.casbin.spring.boot.autoconfigure.properties.CasbinExceptionProperties;
import org.casbin.spring.boot.autoconfigure.properties.CasbinProperties;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.ObjectProvider;
import org.springframework.boot.autoconfigure.AutoConfigureAfter;
import org.springframework.boot.autoconfigure.condition.ConditionalOnBean;
import org.springframework.boot.autoconfigure.condition.ConditionalOnExpression;
import org.springframework.boot.autoconfigure.condition.ConditionalOnMissingBean;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import org.springframework.boot.autoconfigure.jdbc.JdbcTemplateAutoConfiguration;
import org.springframework.boot.context.properties.EnableConfigurationProperties;
import org.springframework.boot.jdbc.DatabaseDriver;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.support.JdbcUtils;
import org.springframework.jdbc.support.MetaDataAccessException;
import org.springframework.util.StringUtils;

import javax.sql.DataSource;
import java.io.InputStream;
import java.sql.DatabaseMetaData;

/**
 * @author fangzhengjin
 * @version V1.0
 * @title: CasbinAutoConfiguration
 * @package org.casbin.spring.boot.autoconfigure
 * @description:
 * @date 2019-4-05 13:53
 */

@Configuration
@EnableConfigurationProperties({CasbinProperties.class, CasbinExceptionProperties.class})
@AutoConfigureAfter({JdbcTemplateAutoConfiguration.class})
@ConditionalOnExpression("${casbin.enableCasbin:true}")
public class CasbinAutoConfiguration {

    private final static Logger logger = LoggerFactory.getLogger(CasbinAutoConfiguration.class);

    /**
     * Automatic configuration file storage adapter
     */
    @Bean
    @ConditionalOnProperty(name = "casbin.storeType", havingValue = "file")
    @ConditionalOnMissingBean
    public Adapter autoConfigFileAdapter(CasbinProperties properties) {
        // if the file storage is chosen and the policy file location is set correctly, then create a file adapter
        if (!StringUtils.isEmpty(properties.getPolicy())) {
            try (InputStream policyInputStream = properties.getPolicyInputStream()) {
                return new FileAdapter(policyInputStream);
            } catch (Exception ignored) {
            }
        }
        throw new CasbinAdapterException("Cannot create file adapter, because policy file is not set");
    }

    /**
     * Automatic configuration of JDBC adapter
     */
    @Bean
    @ConditionalOnProperty(name = "casbin.storeType", havingValue = "jdbc", matchIfMissing = true)
    @ConditionalOnBean(JdbcTemplate.class)
    @ConditionalOnMissingBean
    @SuppressWarnings("SpringJavaInjectionPointsAutowiringInspection")
    public Adapter autoConfigJdbcAdapter(
            @CasbinDataSource ObjectProvider<DataSource> casbinDataSource,
            JdbcTemplate jdbcTemplate,
            CasbinProperties properties,
            CasbinExceptionProperties exceptionProperties
    ) {
        JdbcTemplate jdbcTemplateToUse = getJdbcTemplate(jdbcTemplate, casbinDataSource);
        String databaseName = getDatabaseName(jdbcTemplateToUse.getDataSource());
        CasbinDataSourceInitializationMode initializeSchema = properties.getInitializeSchema();
        boolean autoCreateTable = initializeSchema == CasbinDataSourceInitializationMode.CREATE;
        logger.info("Casbin current use database product: {}", databaseName);
        switch (databaseName) {
            case "mysql":
            case "h2":
                return new JdbcAdapter(jdbcTemplateToUse, exceptionProperties, autoCreateTable);
			case "postgresql":
                return new PostgreSQLAdapter(jdbcTemplateToUse, exceptionProperties, autoCreateTable);
            case "oracle":
                return new OracleAdapter(jdbcTemplateToUse, exceptionProperties, autoCreateTable);
            case "db2":
                return new DB2Adapter(jdbcTemplateToUse, exceptionProperties, autoCreateTable);
            default:
                throw new CasbinAdapterException("Can't find " + databaseName + " jdbc adapter");
        }
    }

    /**
     * Automatic configuration of the enforcer
     */
    @Bean
    @ConditionalOnMissingBean
    @SuppressWarnings("SpringJavaInjectionPointsAutowiringInspection")
    public Enforcer enforcer(CasbinProperties properties, Adapter adapter) {
        Model model = new Model();
        try {
            String modelContext = properties.getModelContext();
            model.loadModelFromText(modelContext);
        } catch (CasbinModelConfigNotFoundException e) {
            // if the local model file address is not set or the file is not found in the default path, the default rbac configuration is used
            if (!properties.isUseDefaultModelIfModelNotSetting()) {
                throw e;
            }
            logger.info("Con't found model config file, use default model config");
            // request definition
            model.addDef("r", "r", "sub, obj, act");
            // policy definition
            model.addDef("p", "p", "sub, obj, act");
            // role definition
            model.addDef("g", "g", "_, _");
            // policy effect
            model.addDef("e", "e", "some(where (p.eft == allow))");
            // matchers
            model.addDef("m", "m", "g(r.sub, p.sub) && r.obj == p.obj && r.act == p.act");
        }
        Enforcer enforcer;
        if (properties.isUseSyncedEnforcer()) {
            enforcer = new SyncedEnforcer(model, adapter);
            logger.info("Casbin use SyncedEnforcer");
        } else {
            enforcer = new Enforcer(model, adapter);
        }
        enforcer.enableAutoSave(properties.isAutoSave());
        return enforcer;
    }

    /**
     * Get the current database type
     */
    private static String getDatabaseName(DataSource dataSource) {
        try {
            String productName = JdbcUtils.
                    commonDatabaseName(JdbcUtils.extractDatabaseMetaData(
                            dataSource, DatabaseMetaData::getDatabaseProductName
                    ));
            DatabaseDriver databaseDriver = DatabaseDriver.fromProductName(productName);
            if (databaseDriver == DatabaseDriver.UNKNOWN) {
                throw new IllegalStateException("Unable to detect database type");
            }
            return databaseDriver.getId();
        } catch (MetaDataAccessException ex) {
            throw new IllegalStateException("Unable to detect database type", ex);
        }
    }

    private static JdbcTemplate getJdbcTemplate(JdbcTemplate jdbcTemplate, ObjectProvider<DataSource> dataSource) {
        DataSource dataSourceIfAvailable = dataSource.getIfAvailable();
        if (dataSourceIfAvailable != null) {
            logger.info("Discover the custom Casbin data source.");
            return new JdbcTemplate(dataSourceIfAvailable);
        } else {
            logger.info("Casbin is using the data source managed by Spring.");
            return jdbcTemplate;
        }
    }
}
```

**Comment by hsluoyz** [comment]
@shink

**Comment by shink** [comment]
@hsluoyz OK, I will.

**Comment by hsluoyz** [comment]
@byrebg for a new issue, please send a new github issue.

**Comment by byrebg** [comment]
Thanks for the quick support
