### ISSUE TITLE
JDBCAdapter only support fixed table name

### ISSUE THREAD

**Issue by doctormacky** [apache/casbin-spring-boot-starter#51]
Hi guys, when customer using this project.  the table name are fixed.(casbin_rule) we need a way to support the configurable table name.  I will submit PR whe I am available.

**Comment by hsluoyz** [comment]
@doctormacky can you make a PR for this?

BTW, it's "adapter" instead of "adaptor" :)

**Comment by doctormacky** [comment]
> 

Will do when I am available.
