### ISSUE TITLE
JdbcAdapter will not load the policy from database in initial phase

### ISSUE THREAD

**Issue by doctormacky** [apache/casbin-spring-boot-starter#53]
When we try to run the springboot, it will not load existing policy from database.  that means the poliicy in memoy of the appliication are empty, this should not work as expected.

from my understanding,  the adapter should load all the policy from database during the initial phase of application. 
Suggest we set following attribute in JdbcAdapter from true to false as default. 
` private volatile boolean isFiltered = false ;`

Any idea ?

**Comment by hsluoyz** [comment]
@fangzhengjin

**Comment by hsluoyz** [comment]
@seriouszyx can you take a look?

**Comment by seriouszyx** [comment]
@doctormacky The `isFilter` value has been set as _false_ in https://github.com/jcasbin/casbin-spring-boot-starter/pull/58.

**Comment by hsluoyz** [comment]
Resolved.
