### ISSUE TITLE
Replace jacsbin 1.9.2 in casbin-spring-boot-starter with version 1.21.0

### ISSUE THREAD

**Issue by ningL32** [apache/casbin-spring-boot-starter#56]
`
<dependency>
            <groupId>org.casbin</groupId>
            <artifactId>casbin-spring-boot-starter</artifactId>
            <version>0.3.0</version>
           <exclusions>
                <exclusion>
                    <groupId>org.casbin</groupId>
                    <artifactId>jcasbin</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
       <dependency>
            <groupId>org.casbin</groupId>
            <artifactId>jcasbin</artifactId>
            <version>1.21.0</version>
        </dependency>
`
Since jacsbin 1.9.2 does not support batch operations, we use 1.21.0, but after changing the version, 1.9.2 can enforce the permissions of true, now all are false, and there is no change in mode.conf and library data. Please fix it or introduce the latest version of jcasbin

**Comment by seriouszyx** [comment]
Please use English. I'm Working on it.

**Comment by seriouszyx** [comment]
Sorry, `JdbcAdapter` has not yet implemented the `UpdatableAdapter` interface. So when using the update API, the data is not synchronized to the database even if autosave is enabled. Currently, you can manually call `savePolicy` after each call to the update API. We will implement the interface later.

**Comment by hsluoyz** [comment]
@seriouszyx any progress?
