### ISSUE TITLE
Support for policy subset loading

### ISSUE THREAD

**Issue by ssafayet** [apache/casbin-spring-boot-starter#57]
How to use policy subset loading here? I am not able to find any documentation regarding this. Note that I am using JDBC with postgres.

**Comment by seriouszyx** [comment]
Hi, you can find some unit tests [here](https://github.com/jcasbin/casbin-spring-boot-starter/blob/master/src/test/java/org/casbin/adapter/JdbcAdapterTest.java) for reference.
