### ISSUE TITLE
RedisWatcherAutoConfigration bug

### ISSUE THREAD

**Issue by ShingmoYeung** [apache/casbin-spring-boot-starter#86]
in

>  src/main/java/org/casbin/spring/boot/autoconfigure/CasbinRedisWatcherAutoConfiguration.java

casbinProperties.getPolicyTopic() should be passed in, not redisProperties.getClientName().

`// fixed channel-name
RedisWatcher watcher = new RedisWatcher(redisProperties.getHost(), redisProperties.getPort(), casbinProperties.getPolicyTopic(), timeout, redisProperties.getPassword());`

**Comment by hsluoyz** [comment]
@ShingmoYeung hi, can you make a PR to fix it?

**Comment by ShingmoYeung** [comment]
@hsluoyz sure
