### ISSUE TITLE
unable to refresh roles for user

### ISSUE THREAD

**Issue by liamashes** [apache/casbin-spring-boot-starter#88]
First, two roles were added to alice in the configuration table, and her role information was also obtained normally.

<img width="396" alt="image" src="https://github.com/jcasbin/casbin-spring-boot-starter/assets/65932272/915e2a6d-0f54-4da5-8a8b-a26e1e6497ea">

<img width="459" alt="image" src="https://github.com/jcasbin/casbin-spring-boot-starter/assets/65932272/dab391b7-13eb-4955-8f01-91a3f01fcaa8">

But after adding a third role, it still doesn't get it after a long time, and the config is set to auto-refresh.
<img width="381" alt="image" src="https://github.com/jcasbin/casbin-spring-boot-starter/assets/65932272/a82ebaa7-e747-40df-9c2f-604fdff96e40">

<img width="438" alt="image" src="https://github.com/jcasbin/casbin-spring-boot-starter/assets/65932272/98b44c31-d874-41e0-b0c2-31a7dc345f5c">

<img width="384" alt="image" src="https://github.com/jcasbin/casbin-spring-boot-starter/assets/65932272/7c4a3b09-3148-46e1-b6e1-81f91807338d">

![image](https://github.com/jcasbin/casbin-spring-boot-starter/assets/65932272/2fce814e-705d-41de-8fd0-ed3bf68c40ee)

What is the problem?

**Comment by imp2002** [comment]
Insert data with `SQL INSERT` directly into the database？ Casbin enforce won't update, you need call `loadPolicy()`. `enableWatcher` work for mutil casbin node rather than database change notify `enforce`.

**Comment by hsluoyz** [comment]
@liamashes use watcher: https://casbin.org/docs/watchers , don't modify DB by yourself
