### ISSUE TITLE
关于springboot集成casbin

### ISSUE THREAD

**Issue by shangchaoshi** [apache/casbin-spring-boot-starter#9]
原项目采用springboot4构成，配置文件如下。集成casbin的时候会报错
![I@GM C7U6 YTNHAGY(TMUIS](https://user-images.githubusercontent.com/52398600/60416155-aea4f700-9c0f-11e9-9ff2-0b8fd63749b9.png)

项目配置文件如下
![L73QR(A}3NEK %YTICEA0H](https://user-images.githubusercontent.com/52398600/60416232-e1e78600-9c0f-11e9-8126-c7d2aaf36c62.png)
![X132TM4O2L)M 955D4I2R{H](https://user-images.githubusercontent.com/52398600/60416290-07748f80-9c10-11e9-8d9f-f5819914b33c.png)
@fangzhengjin

**Comment by fangzhengjin** [comment]
spring4的直接使用虽然没有测试过，但是跟boot差别应该不大，看错错误提示应该是没加载到casbin 依赖，可以尝试手动添加下试试！
https://github.com/casbin/jcasbin

**Comment by hsluoyz** [comment]
Please use English everywhere to make Casbin an international project.

**Comment by fangzhengjin** [comment]
Or your current version does not support spring @Nullable annotations, you can try to update the spring version.

**Comment by shangchaoshi** [comment]
> Or your current version does not support spring @nullable annotations, you can try to update the spring version.

spring4 do not supported @nullable annotations，it needs update to spring5, but my project is too complex, is there any other way to solve it?

**Comment by fangzhengjin** [comment]
Do you need a watcher for your project?Do you need a watcher for your project?

**Comment by fangzhengjin** [comment]
Do you need a watcher for your project?

**Comment by fangzhengjin** [comment]
If you need to use watcher, please set `casbin.enableWatcher=true` to try

**Comment by shangchaoshi** [comment]
> If you need to use watcher, please set `casbin.enableWatcher=true` to try

i don't need it, no matter how i set it up，still reporting that error

**Comment by fangzhengjin** [comment]
Which spring version are you using? I tried to modify it.

**Comment by shangchaoshi** [comment]
> Which spring version are you using? I tried to modify it.
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>1.5.9.RELEASE</version>
	</parent>

springboot 1.5.9, it dependencys on spring4

**Comment by fangzhengjin** [comment]
Version 0.0.8 has been released. If you use `maven.aliyun.com` , you can get it immediately. If you use the central repository, you need to wait for two hours.
