### ISSUE TITLE
Could you add JDK information to the docs?

### ISSUE THREAD

**Issue by Lordfiber** [apache/casbin-spring-boot-starter#90]
While running this project, I kept encountering errors and thought it might be a configuration issue, which took me a long time to troubleshoot. Eventually, I noticed in the 'specialThank' section, there was a mention of Java 17. After switching to that JDK version, the project was able to run successfully

**Comment by hsluoyz** [comment]
Good idea

**Comment by Lordfiber** [comment]
Thanks for reply. So if I would like to put a proposals next time that all should be written in English？
