### ISSUE TITLE
I want to add multiple sets of Casbin configurations. How should I write the code for this? 

### ISSUE THREAD

**Issue by wcz0** [apache/casbin-spring-boot-starter#91]
I want to add multiple sets of Casbin configurations. How should I write the code for this?

**Comment by hsluoyz** [comment]
@wcz0 can you provide a justification about why need do this?

**Comment by wcz0** [comment]
> @wcz0 can you provide a justification about why need do this?

Because multiple sets of permissions management is a common feature in a project, refer to https://github.com/php-casbin/laravel-authz?tab=readme-ov-file#multiple-enforcers.
Is there any method to easily implement multiple enforcers?

**Comment by hsluoyz** [comment]
@ailiujiarui
