### ISSUE TITLE
Dependency conflict + wrong tag for dependency jcasbin

### ISSUE THREAD

**Issue by loukkyy** [apache/casbin-spring-boot-starter#92]
The following dependency creates a conflict for jcasbin:
https://github.com/jcasbin/casbin-spring-boot-starter/blob/c24ff1b7d7a9ed6d9cb89a6a304076edcfa81001/build.gradle#L47

Also, it is not using a correct tagging ("LATEST")
![image](https://github.com/jcasbin/casbin-spring-boot-starter/assets/41201608/308a8e12-4d0e-4ae9-ae40-ff170684725d)

**Workaround**
Exclude jcasbin dependency from and re-import it as follows:
```xml
<dependency>
	<groupId>org.casbin</groupId>
	<artifactId>casbin-spring-boot-starter</artifactId>
	<version>1.2.0</version>
	<exclusions>
		<exclusion>
			<artifactId>jcasbin</artifactId>
			<groupId>org.casbin</groupId>
		</exclusion>
	</exclusions>
</dependency>
<dependency>
	<groupId>org.casbin</groupId>
	<artifactId>jcasbin</artifactId>
	<version>1.40.0</version>
</dependency>
```

**Comment by hsluoyz** [comment]
@loukkyy hi, can you make a PR to fix it?
