### ISSUE TITLE
Failed to release new Maven package

### ISSUE THREAD

**Issue by hsluoyz** [apache/casbin-spring-boot-starter#95]
The semantic release already executes successfully and has github release:

![image](https://github.com/jcasbin/casbin-spring-boot-starter/assets/3787410/d0fe9304-5f1c-4915-8154-9f4b2537e882)

But Maven doesn't have new release: https://mvnrepository.com/artifact/org.casbin/casbin-spring-boot-starter

Why?

![image](https://github.com/jcasbin/casbin-spring-boot-starter/assets/3787410/176d47fe-380e-4c0e-b991-015bde836e44)

It seems that the semantic-release step has already run without issue: https://github.com/jcasbin/casbin-spring-boot-starter/actions/runs/8211424309/job/22460326826

![image](https://github.com/jcasbin/casbin-spring-boot-starter/assets/3787410/45c8a04c-4215-4b85-ad00-adb012a0da00)

**Comment by imp2002** [comment]
This is normal. We will need to wait for a while, it will take approximately 24 hours for the release to be synced to `mvnrepository` and become searchable.

**Comment by hsluoyz** [comment]
Got it, thanks for explanation
